### ISSUE TITLE
So where are the settings to actually enable any of the features?

### ISSUE THREAD

**Issue by Arseniy-Popov** [Kalbra/NoReel#25]
Can't find them anywhere.

**Comment by Kalbra** [comment]
Hi @Arseniy-Popov, I've looked into it and actually the settings button was not showing. I fixed this problem in the latest release.
https://github.com/Kalbra/NoReel/releases/tag/v2.0.1 You have to reinstall the app and cannot update it, due to signing reasons.
You can reach the settings on your account page (right bottom). There should be a orange settings button. If not please let me know.
